### ISSUE TITLE
Some config key error occurred

### ISSUE THREAD

**Issue by Peter-SungwooCho** [choijeongsoo/lip2speech-unit#13]
I got some error when I follow the guidance for train the multi_target_lip2speech.

Here is the error!

```
Traceback (most recent call last):
  File "/home/sungwoo/lip2speech-unit-dev/fairseq/fairseq_cli/hydra_train.py", line 27, in hydra_main
    _hydra_main(cfg)
  File "/home/sungwoo/lip2speech-unit-dev/fairseq/fairseq_cli/hydra_train.py", line 56, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/home/sungwoo/lip2speech-unit-dev/fairseq/fairseq/distributed/utils.py", line 404, in call_main
    main(cfg, **kwargs)
  File "/home/sungwoo/lip2speech-unit-dev/fairseq/fairseq_cli/train.py", line 96, in main
    model = task.build_model(cfg.model)
  File "/home/sungwoo/lip2speech-unit-dev/fairseq/fairseq/tasks/fairseq_task.py", line 355, in build_model
    model = models.build_model(cfg, self, from_checkpoint)
  File "/home/sungwoo/lip2speech-unit-dev/fairseq/fairseq/models/__init__.py", line 106, in build_model
    return model.build_model(cfg, task)
  File "/home/sungwoo/lip2speech-unit-dev/multi_target_lip2speech/model_avhubert.py", line 79, in build_model
    task_pretrain = tasks.setup_task(w2v_args.task)
  File "/home/sungwoo/lip2speech-unit-dev/fairseq/fairseq/tasks/__init__.py", line 40, in setup_task
    cfg = merge_with_parent(dc(), cfg, remove_missing=remove_missing)
  File "/home/sungwoo/lip2speech-unit-dev/fairseq/fairseq/dataclass/utils.py", line 507, in merge_with_parent
    merged_cfg = OmegaConf.merge(dc, cfg)
omegaconf.errors.ConfigKeyError: Key 'input_modality' not in 'AVHubertPretrainingConfig'
        full_key: input_modality
        reference_type=Optional[AVHubertPretrainingConfig]
        object_type=AVHubertPretrainingConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Can I know why this kind of things happening?

I have experience training avhubert models, but this is the first time I've seen an error like this.

**Comment by choijeongsoo** [comment]
Hi, I've added a placeholder for compatibility in the latest commit https://github.com/choijeongsoo/lip2speech-unit/commit/0c96388a064ad18343c23b2ad6f1737b8ab84aa5.

Please check the changes and this might resolve the issue.

**Comment by Peter-SungwooCho** [comment]
Thanks a lot!! Have a nice day:)
